package repo

import (
	"context"
	"fmt"
)

// KeyCeremonyLogRepo is the idcd_attest.key_ceremony_log data-access
// surface. The table is append-only; deletion is not supported at the
// repo level. Inserts are gated by the dual-approval flow in
// docs/prd/11-admin.md — this layer only persists the resulting record.
type KeyCeremonyLogRepo struct {
	pool Pool
}

const keyCeremonyLogColumns = `id, action, key_id, key_version,
	actors, evidence_url, notes, created_at`

const keyCeremonyLogInsertSQL = `
	INSERT INTO idcd_attest.key_ceremony_log (
		id, action, key_id, key_version,
		actors, evidence_url, notes, created_at
	) VALUES (
		$1, $2, $3, $4,
		$5, $6, $7, COALESCE($8, now())
	)
`

// Insert persists a new key-ceremony record. The id (kc_*) must be
// generated by the caller. Returns ErrConflict on UNIQUE-PK violation.
func (r *KeyCeremonyLogRepo) Insert(ctx context.Context, k *KeyCeremony) error {
	if k == nil {
		return fmt.Errorf("key_ceremony_log insert: nil ceremony")
	}
	var createdAt any
	if !k.CreatedAt.IsZero() {
		createdAt = k.CreatedAt
	}
	_, err := r.pool.Exec(ctx, keyCeremonyLogInsertSQL,
		k.ID,
		k.Action,
		k.KeyID,
		k.KeyVersion,
		k.Actors,
		k.EvidenceURL,
		k.Notes,
		createdAt,
	)
	if err != nil {
		if isUniqueViolation(err) {
			return ErrConflict
		}
		return fmt.Errorf("key_ceremony_log insert: %w", err)
	}
	return nil
}

const keyCeremonyLogListSQL = `
	SELECT ` + keyCeremonyLogColumns + `
	FROM idcd_attest.key_ceremony_log
	ORDER BY created_at DESC
	LIMIT $1 OFFSET $2
`

// List returns key-ceremony records ordered by created_at DESC (newest
// first). Used by the admin audit view.
func (r *KeyCeremonyLogRepo) List(ctx context.Context, limit, offset int) ([]*KeyCeremony, error) {
	rows, err := r.pool.Query(ctx, keyCeremonyLogListSQL, limit, offset)
	if err != nil {
		return nil, fmt.Errorf("key_ceremony_log list: %w", err)
	}
	defer rows.Close()

	out := make([]*KeyCeremony, 0)
	for rows.Next() {
		k, scanErr := scanKeyCeremony(rows)
		if scanErr != nil {
			return nil, fmt.Errorf("key_ceremony_log list scan: %w", scanErr)
		}
		out = append(out, k)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("key_ceremony_log list rows: %w", err)
	}
	return out, nil
}

func scanKeyCeremony(r rowScanner) (*KeyCeremony, error) {
	var k KeyCeremony
	if err := r.Scan(
		&k.ID,
		&k.Action,
		&k.KeyID,
		&k.KeyVersion,
		&k.Actors,
		&k.EvidenceURL,
		&k.Notes,
		&k.CreatedAt,
	); err != nil {
		return nil, err
	}
	return &k, nil
}
