package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

// TsaResponsesRepo is the idcd_attest.tsa_response data-access surface.
// Stores one row per TSA call regardless of outcome — including probes
// not attached to a report — so the Multi TSA health monitor can score
// each provider's success / failure / timeout mix.
type TsaResponsesRepo struct {
	pool Pool
}

const tsaResponseColumns = `id, provider, request_hash, response_blob,
	serial_number, issued_at, valid_until, status, latency_ms,
	used_by_report_id, created_at`

const tsaResponseInsertSQL = `
	INSERT INTO idcd_attest.tsa_response (
		id, provider, request_hash, response_blob,
		serial_number, issued_at, valid_until, status, latency_ms,
		used_by_report_id, created_at
	) VALUES (
		$1, $2, $3, $4,
		$5, $6, $7, $8, $9,
		$10, COALESCE($11, now())
	)
`

// Insert persists a new TSA response record (success, failure or
// timeout). The id (tsa_*) must be generated by the caller. Returns
// ErrConflict on UNIQUE-PK violation.
func (r *TsaResponsesRepo) Insert(ctx context.Context, t *TSAResponse) error {
	if t == nil {
		return fmt.Errorf("tsa_response insert: nil response")
	}
	var createdAt any
	if !t.CreatedAt.IsZero() {
		createdAt = t.CreatedAt
	}
	_, err := r.pool.Exec(ctx, tsaResponseInsertSQL,
		t.ID,
		t.Provider,
		t.RequestHash,
		t.ResponseBlob,
		t.SerialNumber,
		t.IssuedAt,
		t.ValidUntil,
		t.Status,
		t.LatencyMS,
		t.UsedByReportID,
		createdAt,
	)
	if err != nil {
		if isUniqueViolation(err) {
			return ErrConflict
		}
		return fmt.Errorf("tsa_response insert: %w", err)
	}
	return nil
}

const tsaResponseGetByIDSQL = `
	SELECT ` + tsaResponseColumns + `
	FROM idcd_attest.tsa_response
	WHERE id = $1
`

// GetByID returns the TSA response with the given id, or ErrNotFound.
func (r *TsaResponsesRepo) GetByID(ctx context.Context, id string) (*TSAResponse, error) {
	row := r.pool.QueryRow(ctx, tsaResponseGetByIDSQL, id)
	t, err := scanTSAResponse(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("tsa_response get: %w", err)
	}
	return t, nil
}

const tsaResponseListByProviderSQL = `
	SELECT ` + tsaResponseColumns + `
	FROM idcd_attest.tsa_response
	WHERE provider = $1 AND created_at >= $2
	ORDER BY created_at DESC
	LIMIT $3
`

// ListByProvider returns the most recent TSA responses for a given
// provider since the supplied timestamp. Used by the health monitor to
// compute per-provider success / failure / timeout ratios for the
// Multi-TSA fallover decision.
func (r *TsaResponsesRepo) ListByProvider(ctx context.Context, provider string, sinceCreatedAt time.Time, limit int) ([]*TSAResponse, error) {
	rows, err := r.pool.Query(ctx, tsaResponseListByProviderSQL, provider, sinceCreatedAt, limit)
	if err != nil {
		return nil, fmt.Errorf("tsa_response list by provider: %w", err)
	}
	defer rows.Close()

	out := make([]*TSAResponse, 0)
	for rows.Next() {
		t, scanErr := scanTSAResponse(rows)
		if scanErr != nil {
			return nil, fmt.Errorf("tsa_response list scan: %w", scanErr)
		}
		out = append(out, t)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("tsa_response list rows: %w", err)
	}
	return out, nil
}

func scanTSAResponse(r rowScanner) (*TSAResponse, error) {
	var t TSAResponse
	if err := r.Scan(
		&t.ID,
		&t.Provider,
		&t.RequestHash,
		&t.ResponseBlob,
		&t.SerialNumber,
		&t.IssuedAt,
		&t.ValidUntil,
		&t.Status,
		&t.LatencyMS,
		&t.UsedByReportID,
		&t.CreatedAt,
	); err != nil {
		return nil, err
	}
	return &t, nil
}
