package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

// VerdictOrdersRepo is the idcd_attest.verdict_order data-access
// surface. Status updates are optimistic-locked on the caller-supplied
// "from" status so concurrent workers cannot stomp each other. D5: the
// refund-retry helpers feed the 5min/30min retry queue and the
// refund_failed → P0 admin dashboard escalation.
type VerdictOrdersRepo struct {
	pool Pool
}

const verdictOrderColumns = `id, owner_id, template, target,
	time_window_start, time_window_end, status,
	price_cny, price_paid_cny, ext_order_id,
	refund_reason, refund_attempt_count, refund_last_error,
	refund_apology_sent_at,
	created_at, paid_at, delivered_at, failed_at, refunded_at`

const verdictOrderInsertSQL = `
	INSERT INTO idcd_attest.verdict_order (
		id, owner_id, template, target,
		time_window_start, time_window_end, status,
		price_cny, price_paid_cny, ext_order_id,
		refund_reason, refund_attempt_count, refund_last_error,
		refund_apology_sent_at,
		created_at, paid_at, delivered_at, failed_at, refunded_at
	) VALUES (
		$1, $2, $3, $4,
		$5, $6, $7,
		$8, $9, $10,
		$11, $12, $13,
		$14,
		COALESCE($15, now()), $16, $17, $18, $19
	)
`

// Insert persists a new verdict_order. The id (v_*) must be generated by
// the caller. Returns ErrConflict on UNIQUE-constraint violation.
func (r *VerdictOrdersRepo) Insert(ctx context.Context, o *Order) error {
	var createdAt any
	if !o.CreatedAt.IsZero() {
		createdAt = o.CreatedAt
	}
	_, err := r.pool.Exec(ctx, verdictOrderInsertSQL,
		o.ID,
		o.OwnerID,
		o.Template,
		o.Target,
		o.TimeWindowStart,
		o.TimeWindowEnd,
		o.Status,
		o.PriceCNY,
		o.PricePaidCNY,
		o.ExtOrderID,
		o.RefundReason,
		o.RefundAttemptCount,
		o.RefundLastError,
		o.RefundApologySentAt,
		createdAt,
		o.PaidAt,
		o.DeliveredAt,
		o.FailedAt,
		o.RefundedAt,
	)
	if err != nil {
		if isUniqueViolation(err) {
			return ErrConflict
		}
		return fmt.Errorf("verdict_order insert: %w", err)
	}
	return nil
}

const verdictOrderGetByIDSQL = `
	SELECT ` + verdictOrderColumns + `
	FROM idcd_attest.verdict_order
	WHERE id = $1
`

// GetByID returns the order with the given id, or ErrNotFound.
func (r *VerdictOrdersRepo) GetByID(ctx context.Context, id string) (*Order, error) {
	row := r.pool.QueryRow(ctx, verdictOrderGetByIDSQL, id)
	o, err := scanOrder(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("verdict_order get: %w", err)
	}
	return o, nil
}

const verdictOrderListByOwnerSQL = `
	SELECT ` + verdictOrderColumns + `
	FROM idcd_attest.verdict_order
	WHERE owner_id = $1
	ORDER BY created_at DESC
	LIMIT $2 OFFSET $3
`

const verdictOrderListByOwnerStatusSQL = `
	SELECT ` + verdictOrderColumns + `
	FROM idcd_attest.verdict_order
	WHERE owner_id = $1 AND status = $2
	ORDER BY created_at DESC
	LIMIT $3 OFFSET $4
`

// ListByOwner returns orders for one owner_id, optionally filtered by a
// single status. Pass status == nil to list all statuses. Ordered by
// created_at DESC.
func (r *VerdictOrdersRepo) ListByOwner(ctx context.Context, ownerID string, status *string, limit, offset int) ([]*Order, error) {
	var (
		rows pgx.Rows
		err  error
	)
	if status != nil {
		rows, err = r.pool.Query(ctx, verdictOrderListByOwnerStatusSQL, ownerID, *status, limit, offset)
	} else {
		rows, err = r.pool.Query(ctx, verdictOrderListByOwnerSQL, ownerID, limit, offset)
	}
	if err != nil {
		return nil, fmt.Errorf("verdict_order list: %w", err)
	}
	defer rows.Close()

	out := make([]*Order, 0)
	for rows.Next() {
		o, scanErr := scanOrder(rows)
		if scanErr != nil {
			return nil, fmt.Errorf("verdict_order list scan: %w", scanErr)
		}
		out = append(out, o)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("verdict_order list rows: %w", err)
	}
	return out, nil
}

const verdictOrderUpdateStatusSQL = `
	UPDATE idcd_attest.verdict_order
	SET status = $1, refund_last_error = COALESCE($2, refund_last_error)
	WHERE id = $3 AND status = $4
`

// UpdateStatus moves an order from fromStatus to toStatus, optimistically
// locked: if the current status no longer matches fromStatus the UPDATE
// affects zero rows and we return ErrInvalidStatus. errReason is passed
// through to refund_last_error for failed/refund_failed transitions;
// nil leaves the column untouched.
func (r *VerdictOrdersRepo) UpdateStatus(ctx context.Context, id, fromStatus, toStatus string, errReason *string) error {
	tag, err := r.pool.Exec(ctx, verdictOrderUpdateStatusSQL, toStatus, errReason, id, fromStatus)
	if err != nil {
		return fmt.Errorf("verdict_order update status: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrInvalidStatus
	}
	return nil
}

const verdictOrderIncrementRefundAttemptSQL = `
	UPDATE idcd_attest.verdict_order
	SET refund_attempt_count = refund_attempt_count + 1,
	    refund_last_error    = $1
	WHERE id = $2
`

// IncrementRefundAttempt bumps refund_attempt_count by 1 and records the
// latest failure reason. Drives the D5 5min/30min retry queue.
func (r *VerdictOrdersRepo) IncrementRefundAttempt(ctx context.Context, id, lastError string) error {
	tag, err := r.pool.Exec(ctx, verdictOrderIncrementRefundAttemptSQL, lastError, id)
	if err != nil {
		return fmt.Errorf("verdict_order increment refund attempt: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

const verdictOrderStampRefundedAtSQL = `
	UPDATE idcd_attest.verdict_order
	SET refunded_at = $1
	WHERE id = $2
`

// StampRefundedAt sets refunded_at on the given order. Called by the
// D5 refund worker immediately after the optimistic-locked UpdateStatus
// that flips status='refunded'. Kept separate so the UpdateStatus
// surface stays focused on the state-machine column.
func (r *VerdictOrdersRepo) StampRefundedAt(ctx context.Context, id string, t time.Time) error {
	tag, err := r.pool.Exec(ctx, verdictOrderStampRefundedAtSQL, t, id)
	if err != nil {
		return fmt.Errorf("verdict_order stamp refunded_at: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

const verdictOrderSetRefundApologySentSQL = `
	UPDATE idcd_attest.verdict_order
	SET refund_apology_sent_at = $1
	WHERE id = $2
`

// SetRefundApologySent stamps the 30-minute apology-email fallback.
// D5: after 30 minutes of failed refund retries we must email the user
// apologising and escalate to refund_failed.
func (r *VerdictOrdersRepo) SetRefundApologySent(ctx context.Context, id string, t time.Time) error {
	tag, err := r.pool.Exec(ctx, verdictOrderSetRefundApologySentSQL, t, id)
	if err != nil {
		return fmt.Errorf("verdict_order set refund_apology_sent_at: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

func scanOrder(r rowScanner) (*Order, error) {
	var o Order
	if err := r.Scan(
		&o.ID,
		&o.OwnerID,
		&o.Template,
		&o.Target,
		&o.TimeWindowStart,
		&o.TimeWindowEnd,
		&o.Status,
		&o.PriceCNY,
		&o.PricePaidCNY,
		&o.ExtOrderID,
		&o.RefundReason,
		&o.RefundAttemptCount,
		&o.RefundLastError,
		&o.RefundApologySentAt,
		&o.CreatedAt,
		&o.PaidAt,
		&o.DeliveredAt,
		&o.FailedAt,
		&o.RefundedAt,
	); err != nil {
		return nil, err
	}
	return &o, nil
}
