export interface ToolDef {
  slug: string
  name: string
  description: string
  category: 'probe' | 'utility'
  metaTitle: string
  metaDescription: string
}

export const ALL_TOOLS: ToolDef[] = [
  // ── 拨测工具（15 个）────────────────────────────────────────────────
  {
    slug: 'ssl',
    name: 'SSL 证书检查',
    description: '检查域名 SSL/TLS 证书有效期和配置',
    category: 'probe',
    metaTitle: 'SSL 证书检查 - 域名证书有效期查询 | idcd',
    metaDescription: '检查域名 SSL/TLS 证书有效期、颁发机构和安全配置。',
  },
  {
    slug: 'whois',
    name: 'WHOIS 查询',
    description: '查询域名注册信息和持有者',
    category: 'probe',
    metaTitle: 'WHOIS 查询 - 域名注册信息查询 | idcd',
    metaDescription: '查询域名注册信息、注册商、过期时间和持有者联系方式。',
  },
  {
    slug: 'icp',
    name: 'ICP 备案查询',
    description: '查询域名 ICP 备案状态',
    category: 'probe',
    metaTitle: 'ICP 备案查询 - 网站备案号查询 | idcd',
    metaDescription: '查询域名 ICP 备案号、备案主体和审核状态。',
  },
  {
    slug: 'ip',
    name: 'IP 地理位置',
    description: '查询 IP 地址的地理位置和 ASN 信息',
    category: 'probe',
    metaTitle: 'IP 地理位置查询 - IP 归属地查询 | idcd',
    metaDescription: '查询 IP 地址的地理位置、运营商、ASN 和归属地信息。',
  },
  {
    slug: 'tcp',
    name: 'TCP 端口测试',
    description: '测试 TCP 端口的连通性',
    category: 'probe',
    metaTitle: 'TCP 端口测试 - TCP 连通性检测 | idcd',
    metaDescription: '测试目标主机 TCP 端口是否可访问，检测端口连通性。',
  },
  {
    slug: 'mtr',
    name: 'MTR 路由测试',
    description: '结合 Ping 和 Traceroute 的网络诊断',
    category: 'probe',
    metaTitle: 'MTR 路由测试 - 网络路径诊断 | idcd',
    metaDescription: 'MTR 网络路由测试工具，结合 Ping 和 Traceroute 功能，诊断网络路径问题。',
  },
  {
    slug: 'smtp',
    name: 'SMTP 邮件测试',
    description: '测试 SMTP 邮件服务器连通性',
    category: 'probe',
    metaTitle: 'SMTP 邮件服务器测试 - 邮件连通性检测 | idcd',
    metaDescription: '测试 SMTP 邮件服务器是否可访问，检测邮件发送服务。',
  },
  {
    slug: 'rdns',
    name: '反向 DNS 查询',
    description: '查询 IP 的反向 DNS 记录（PTR）',
    category: 'probe',
    metaTitle: '反向 DNS 查询 - IP 反查域名 | idcd',
    metaDescription: '通过 IP 地址反查对应的域名（PTR 记录）。',
  },
  {
    slug: 'asn',
    name: 'ASN 查询',
    description: '查询 AS 号对应的网络信息',
    category: 'probe',
    metaTitle: 'ASN 自治系统查询 - ASN 信息查询 | idcd',
    metaDescription: '查询 ASN 自治系统号对应的网络运营商和 IP 段信息。',
  },
  {
    slug: 'mx',
    name: 'MX 记录查询',
    description: '查询域名邮件交换记录',
    category: 'probe',
    metaTitle: 'MX 邮件记录查询 - 域名 MX 记录检测 | idcd',
    metaDescription: '查询域名 MX 邮件交换记录，验证邮件服务配置。',
  },
  {
    slug: 'spf',
    name: 'SPF 记录查询',
    description: '查询域名 SPF 邮件认证记录',
    category: 'probe',
    metaTitle: 'SPF 记录查询 - 邮件发送策略检测 | idcd',
    metaDescription: '查询和验证域名 SPF 发件人策略框架记录。',
  },
  {
    slug: 'dmarc',
    name: 'DMARC 记录查询',
    description: '查询域名 DMARC 邮件认证策略',
    category: 'probe',
    metaTitle: 'DMARC 记录查询 - 邮件认证策略检测 | idcd',
    metaDescription: '查询域名 DMARC 邮件认证报告和合规策略配置。',
  },
  {
    slug: 'ntp',
    name: 'NTP 服务测试',
    description: '测试 NTP 时间同步服务器',
    category: 'probe',
    metaTitle: 'NTP 服务测试 - 时间同步服务检测 | idcd',
    metaDescription: '测试 NTP 网络时间协议服务器的连通性和时间偏差。',
  },
  {
    slug: 'dkim',
    name: 'DKIM 密钥查询',
    description: '查询域名 DKIM 公钥记录',
    category: 'probe',
    metaTitle: 'DKIM 密钥查询 - 邮件签名密钥检测 | idcd',
    metaDescription: '查询域名 DKIM 域名密钥识别邮件公钥记录。',
  },
  {
    slug: 'bgp',
    name: 'BGP 路由查询',
    description: '查询 IP 或前缀的 BGP 路由信息',
    category: 'probe',
    metaTitle: 'BGP 路由查询 - IP 前缀路由信息 | idcd',
    metaDescription: '查询 IP 地址或网络前缀的 BGP 路由路径和 AS 路径信息。',
  },

  // ── 辅助工具（35 个）────────────────────────────────────────────────
  {
    slug: 'yaml-formatter',
    name: 'YAML 格式化',
    description: 'YAML 格式美化和验证',
    category: 'utility',
    metaTitle: 'YAML 格式化工具 - 在线 YAML 美化 | idcd',
    metaDescription: '在线 YAML 格式化、美化工具，支持 YAML 与 JSON 互转。',
  },
  {
    slug: 'xml-formatter',
    name: 'XML 格式化',
    description: 'XML 格式美化和验证',
    category: 'utility',
    metaTitle: 'XML 格式化工具 - 在线 XML 美化 | idcd',
    metaDescription: '在线 XML 格式化、美化和语法验证工具，支持 XML 压缩。',
  },
  {
    slug: 'url-encode',
    name: 'URL 编解码',
    description: 'URL 编码与解码',
    category: 'utility',
    metaTitle: 'URL 编解码工具 - 在线 URL 编码 | idcd',
    metaDescription: '在线 URL 编码解码工具，支持 encodeURIComponent 和 encodeURI 格式。',
  },
  {
    slug: 'unicode',
    name: 'Unicode 转换',
    description: 'Unicode 字符查询与转换',
    category: 'utility',
    metaTitle: 'Unicode 字符转换 - Unicode 码点查询 | idcd',
    metaDescription: '查询 Unicode 字符信息，支持字符与码点的互相转换。',
  },
  {
    slug: 'jwt-decode',
    name: 'JWT 解码',
    description: 'JWT Token 解析工具',
    category: 'utility',
    metaTitle: 'JWT 解码工具 - JSON Web Token 解析 | idcd',
    metaDescription: '在线 JWT Token 解析工具，查看 Header 和 Payload 内容。',
  },
  {
    slug: 'regex',
    name: '正则表达式',
    description: '正则表达式测试与调试',
    category: 'utility',
    metaTitle: '正则表达式测试 - 在线 RegEx 测试 | idcd',
    metaDescription: '在线正则表达式测试工具，实时高亮匹配结果，支持全局/多行等标志。',
  },
  {
    slug: 'cron-viz',
    name: 'Cron 可视化',
    description: 'Cron 表达式解析与下次执行时间',
    category: 'utility',
    metaTitle: 'Cron 表达式可视化 - Cron 解析工具 | idcd',
    metaDescription: '解析 Cron 定时表达式，显示未来执行时间，支持标准 5 段格式。',
  },
  {
    slug: 'cidr-calc',
    name: 'CIDR 计算器',
    description: 'IP 子网和 CIDR 范围计算',
    category: 'utility',
    metaTitle: 'CIDR 子网计算器 - IP 段计算工具 | idcd',
    metaDescription: '计算 CIDR 网段的主机数量、广播地址、子网掩码等信息。',
  },
  {
    slug: 'ipv6-check',
    name: 'IPv6 检测',
    description: 'IPv6 地址检测与格式转换',
    category: 'utility',
    metaTitle: 'IPv6 地址检测 - IPv6 格式转换 | idcd',
    metaDescription: 'IPv6 地址格式验证、扩展/压缩格式转换和类型检测。',
  },
  {
    slug: 'color-picker',
    name: '颜色格式转换',
    description: '颜色格式互转（HEX/RGB/HSL）',
    category: 'utility',
    metaTitle: '颜色格式转换工具 - HEX/RGB/HSL 互转 | idcd',
    metaDescription: '在线颜色格式转换工具，支持 HEX、RGB、HSL 格式互相转换并预览颜色。',
  },
  {
    slug: 'markdown',
    name: 'Markdown 预览',
    description: 'Markdown 编辑与实时预览',
    category: 'utility',
    metaTitle: 'Markdown 预览工具 - 在线 Markdown 渲染 | idcd',
    metaDescription: '在线 Markdown 编辑和实时预览工具，无需安装。',
  },
  {
    slug: 'diff',
    name: '文本对比',
    description: '文本内容逐行差异比较',
    category: 'utility',
    metaTitle: '文本对比工具 - 在线文本差异比较 | idcd',
    metaDescription: '在线文本差异比较工具，逐行对比两段文本内容的差异。',
  },
  {
    slug: 'word-counter',
    name: '字数统计',
    description: '文本字数、字符数、行数统计',
    category: 'utility',
    metaTitle: '字数统计工具 - 在线文本计数 | idcd',
    metaDescription: '统计文本字数、字符数、行数和段落数，支持中英文混合计数。',
  },
  {
    slug: 'password-gen',
    name: '密码生成器',
    description: '安全随机密码生成',
    category: 'utility',
    metaTitle: '密码生成器 - 随机安全密码生成 | idcd',
    metaDescription: '生成高强度随机密码，支持自定义长度和字符集。',
  },
  {
    slug: 'uuid-gen',
    name: 'UUID 生成器',
    description: 'UUID v4 批量生成工具',
    category: 'utility',
    metaTitle: 'UUID 生成器 - 在线 UUID v4 生成 | idcd',
    metaDescription: '在线生成 UUID v4 唯一标识符，支持批量生成。',
  },
  {
    slug: 'number-convert',
    name: '进制转换',
    description: '数字进制（二/八/十/十六）互转',
    category: 'utility',
    metaTitle: '数字进制转换 - 二进制十六进制转换 | idcd',
    metaDescription: '在线进制转换工具，支持二进制、八进制、十进制、十六进制互转。',
  },
  {
    slug: 'text-case',
    name: '大小写转换',
    description: '文本大小写批量转换',
    category: 'utility',
    metaTitle: '文本大小写转换 - camelCase/snake_case | idcd',
    metaDescription: '在线文本大小写转换，支持 camelCase、snake_case、PascalCase 等格式。',
  },
  {
    slug: 'html-encode',
    name: 'HTML 实体编码',
    description: 'HTML 实体编码与解码',
    category: 'utility',
    metaTitle: 'HTML 实体编码工具 - HTML 转义 | idcd',
    metaDescription: '在线 HTML 实体编码解码工具，转义特殊字符防止 XSS 攻击。',
  },
  {
    slug: 'json-to-yaml',
    name: 'JSON ↔ YAML',
    description: 'JSON 与 YAML 格式互转',
    category: 'utility',
    metaTitle: 'JSON/YAML 互转工具 - 格式转换 | idcd',
    metaDescription: 'JSON 与 YAML 格式互相转换工具，支持格式验证。',
  },
  {
    slug: 'url-parser',
    name: 'URL 解析',
    description: 'URL 各部分解析展示',
    category: 'utility',
    metaTitle: 'URL 解析工具 - URL 结构解析 | idcd',
    metaDescription: '解析 URL 各个组成部分：协议、域名、路径、参数等。',
  },
  {
    slug: 'user-agent',
    name: 'UA 解析',
    description: 'User-Agent 字符串解析',
    category: 'utility',
    metaTitle: 'User-Agent 解析工具 - 浏览器识别 | idcd',
    metaDescription: '解析 User-Agent 字符串，识别浏览器、操作系统和设备类型。',
  },
  {
    slug: 'http-status',
    name: 'HTTP 状态码',
    description: 'HTTP 响应状态码查询',
    category: 'utility',
    metaTitle: 'HTTP 状态码查询 - HTTP 响应码大全 | idcd',
    metaDescription: '查询 HTTP 状态码含义，涵盖 1xx/2xx/3xx/4xx/5xx 所有状态码。',
  },
  {
    slug: 'mime-type',
    name: 'MIME 类型',
    description: '文件 MIME 类型查询',
    category: 'utility',
    metaTitle: 'MIME 类型查询 - 文件类型大全 | idcd',
    metaDescription: '查询文件扩展名对应的 MIME 类型，或反查 MIME 类型对应的文件扩展名。',
  },
  {
    slug: 'timezone',
    name: '时区转换',
    description: '全球时区时间转换',
    category: 'utility',
    metaTitle: '时区转换工具 - 全球时区查询 | idcd',
    metaDescription: '在线时区转换工具，查看全球主要时区的当前时间。',
  },
  {
    slug: 'date-calc',
    name: '日期计算',
    description: '日期差值和加减计算',
    category: 'utility',
    metaTitle: '日期计算工具 - 日期差值计算 | idcd',
    metaDescription: '计算两个日期之间的天数差，或在日期上加减天数。',
  },
  {
    slug: 'image-base64',
    name: '图片 Base64',
    description: '图片转 Base64 编码',
    category: 'utility',
    metaTitle: '图片 Base64 转换 - 图片转 Data URL | idcd',
    metaDescription: '将图片文件转换为 Base64 编码的 Data URL，方便内嵌使用。',
  },
  {
    slug: 'csv-formatter',
    name: 'CSV 格式化',
    description: 'CSV 数据解析和表格展示',
    category: 'utility',
    metaTitle: 'CSV 格式化工具 - CSV 数据解析 | idcd',
    metaDescription: '在线 CSV 格式化工具，将 CSV 数据转换为表格展示。',
  },
  {
    slug: 'number-format',
    name: '数字格式化',
    description: '数字千分位和货币格式化',
    category: 'utility',
    metaTitle: '数字格式化工具 - 千分位货币格式 | idcd',
    metaDescription: '在线数字格式化工具，支持千分位分隔、货币格式和自定义精度。',
  },
  {
    slug: 'lorem',
    name: 'Lorem Ipsum',
    description: 'Lorem Ipsum 占位文本生成',
    category: 'utility',
    metaTitle: 'Lorem Ipsum 生成器 - 占位文字生成 | idcd',
    metaDescription: '生成 Lorem Ipsum 拉丁文占位文本，支持段落数量自定义。',
  },
  {
    slug: 'line-sort',
    name: '行排序',
    description: '文本行排序（正序/倒序）',
    category: 'utility',
    metaTitle: '文本行排序工具 - 在线文本排序 | idcd',
    metaDescription: '对文本按行排序（正序/倒序），支持去重和忽略大小写。',
  },
  {
    slug: 'duplicate-remover',
    name: '去重工具',
    description: '文本行去重，保留唯一行',
    category: 'utility',
    metaTitle: '文本去重工具 - 在线重复行删除 | idcd',
    metaDescription: '删除文本中的重复行，保留唯一行。',
  },
  {
    slug: 'text-stats',
    name: '文本统计',
    description: '词频统计与文本分析',
    category: 'utility',
    metaTitle: '文本统计分析工具 - 字频统计 | idcd',
    metaDescription: '统计文本中的词频、字符频率、句子数量等详细信息。',
  },
  {
    slug: 'escape-html',
    name: 'HTML 转义',
    description: 'HTML 内容安全转义',
    category: 'utility',
    metaTitle: 'HTML 转义工具 - HTML 安全转义 | idcd',
    metaDescription: '将 HTML 内容转义为安全的文本格式，防止 XSS 注入。',
  },
  {
    slug: 'chmod-calc',
    name: 'chmod 计算',
    description: 'Unix 文件权限可视化计算',
    category: 'utility',
    metaTitle: 'chmod 权限计算器 - Unix 文件权限 | idcd',
    metaDescription: '可视化计算 Unix/Linux 文件权限，支持八进制和符号表示法互转。',
  },
  {
    slug: 'sort-json',
    name: 'JSON 键排序',
    description: 'JSON 对象键按字母序排序',
    category: 'utility',
    metaTitle: 'JSON 键排序工具 - JSON 格式整理 | idcd',
    metaDescription: '将 JSON 对象的键按字母顺序排序，方便对比和版本管理。',
  },
]

export const PROBE_TOOLS = ALL_TOOLS.filter(t => t.category === 'probe')
export const UTILITY_TOOLS = ALL_TOOLS.filter(t => t.category === 'utility')

export function getToolBySlug(slug: string): ToolDef | undefined {
  return ALL_TOOLS.find(t => t.slug === slug)
}
